# Generated by Django 3.2.4 on 2023-03-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20230226_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=160, null=True),
        ),
    ]
