# Generated by Django 3.2.4 on 2023-04-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
